services: 
  mynginx:
    build: ./mynginx
    image: vinitkulkarni/mynginx_image:latest
    container_name: nginx_container
    hostname: nginx_container
    ports:
      - "8080:8000"
    networks:
      - dpdzero_network
    depends_on:
      - service_1
      - service_2

  service_1:
    build: ./service_1
    image: vinitkulkarni/service1_image:latest
    container_name: service1
    hostname: service1
    ports:
      - "8001:8001"
    networks:
      - dpdzero_network

  service_2:
    build: ./service_2
    image: vinitkulkarni/service2_image:latest
    container_name: service2
    hostname: service2
    ports:
      - "8002:8002"
    networks:
      - dpdzero_network

networks:
  dpdzero_network:
    driver: bridge
