# Use the official nginx image
FROM nginx:alpine

# Specify maintainer/author information
LABEL maintainer="VINIT KULKARNI"

# Copy the HTML file to the nginx server
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

#this is profession page docker image
